name: Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  merge-to-main:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "mehdi-benhariz"
          git config --global user.email "benharizmehdi20@gmail.com" 
      - name: Fetch the branch
        run: |
          git config --global pull.rebase false
          git fetch origin main

      - name: Switch to the branch
        run: git checkout main

      - name: Merge branch with dev
        run: git merge --no-ff --allow-unrelated-histories dev || true

      - name: Push changes
        run: git push origin main